services:
  - type: web
    name: tigermemory
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TIGER_CLOUD_CONNECTION_STRING
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: info